# Generated by Django 4.0.2 on 2023-07-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.CharField(max_length=50, verbose_name='メインテキスト')),
                ('sub_text', models.TextField(verbose_name='サブテキスト')),
            ],
            options={
                'db_table': 'sample',
            },
        ),
    ]
