version: '3'

services:

  # データベース
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgers_data:/var/lib/postgresql/data

  # django
  web:
    build:
    command: python manage.py runserver 0.0.0.8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgers_data
